name: Build JAR

on:
  workflow_dispatch:
  push:
    branches:
      - "26.1"
      - "sodium-0.9.1-mc26.1.2"

permissions:
  contents: read

env:
  JAVA_VERSION: 25

jobs:
  build:
    name: Build mod JAR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build --no-daemon

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SodiumCoreShaderSupport-${{ github.ref_name }}
          path: |
            build/libs/*.jar
            !build/libs/*-sources.jar
            !build/libs/*-dev.jar
          if-no-files-found: error
          retention-days: 30
